---
name: Conociendo la sintaxis de SQL
locale: es
type: learning
beta: false
teacher_info: Trabajo de Inserción Profesional, Universidad Nacional de Quilmes, Julio
  2017
language: sqlite
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
