---
name: Primeros pasos en SQL
locale: es
type: learning
beta: false
teacher_info: Trabajo de Inserción Profesional, Universidad Nacional de Quilmes, Julio
  2017
language: sqlite
id_format: "%05d"
order:
- 1
